In [1]:
'''
{
"info": info, "images": [image], "annotations": [annotation], "licenses": [license],
}
 
info{
"year": int, "version": str, "description": str, "contributor": str, "url": str, "date_created": datetime,
}
 
image{
"id": int, "width": int, "height": int, "file_name": str, "license": int, "flickr_url": str, "coco_url": str, "date_captured": datetime,
}
 
license{
"id": int, "name": str, "url": str,
}
 
annotation{
"id": int, "image_id": int, "category_id": int, "segmentation": RLE or [polygon], "area": float, "bbox": [x,y,width,height], "iscrowd": 0 or 1,
}
 
categories[{
"id": int, "name": str, "supercategory": str,
}]
'''

'\n{\n"info": info, "images": [image], "annotations": [annotation], "licenses": [license],\n}\n \ninfo{\n"year": int, "version": str, "description": str, "contributor": str, "url": str, "date_created": datetime,\n}\n \nimage{\n"id": int, "width": int, "height": int, "file_name": str, "license": int, "flickr_url": str, "coco_url": str, "date_captured": datetime,\n}\n \nlicense{\n"id": int, "name": str, "url": str,\n}\n \nannotation{\n"id": int, "image_id": int, "category_id": int, "segmentation": RLE or [polygon], "area": float, "bbox": [x,y,width,height], "iscrowd": 0 or 1,\n}\n \ncategories[{\n"id": int, "name": str, "supercategory": str,\n}]\n'

In [12]:
from datetime import datetime
import tensorflow_datasets as tfds
import json
 
class image:
    def __init__(self, id: int, width: int, height: int, file_name: str, license: int, flickr_url: str, coco_url: str, date_captured: datetime):
        self.id = id
        self.width = width
        self.height = height
        self.file_name = file_name
        self.license = license
        self.flickr_url = flickr_url
        self.coco_url = coco_url
        self.date_captured = date_captured
 
class license:
    def __init__(self, id: int, name: str, url: str):
        self.id = id
        self.name = name
        self.url = url
 
class bbox:
    def __init__(self, x: int, y: int, width: int, height: int):
        self.x = x
        self.y = y
        self.width = width
        self.height = height
 
class annotation:
    def __init__(self, id: int, image_id: int, category_id: int, segmentation, area: float, bbox: bbox, iscrowd: bool):
        self.id = id
        self.image_id = image_id
        self.category_id: category_id
        self.segmentation = segmentation
        self.area = area
        self.bbox = list(vars(bbox).values())
        self.iscrowd = iscrowd
 
class category:
    def __init__(self, id: int, name: str, supercategory: str):
        self.id = id
        self.name = name
        self.supercategory = supercategory
 
info = {
        "year": int,
        "version": str,
        "description": str,
        "contributor": str,
        "url": str,
        "date_created": datetime,
        }
 
images = []
annotations = []
licenses = []
categories = [category(0, "None", None), category(1, "Pollen", None), category(2, "Cooling", None), category(3, "Wasp", None)]
[print(list(vars(category).values())) for category in categories]

ds = tfds.load('bee_dataset', split='train')
ds = ds.take(1)  # Only take a single example

for example in ds:  # example is `{'image': tf.Tensor, 'label': tf.Tensor}`
    print(list(example.keys()))
    image = example["input"]
    label = example["output"]
    print(image.shape, label)

# Id =
# Width =
# Height =
# File_name =
# License =
Flickr_url = None
Coco_url = None
Date_captured = datetime.now()
 
# images.append(image(Id, Width, Height, File_name, License, Flickr_url, Coco_url, Date_captured))
 
# Annotation_Id =
# Image_id =
# Category_id =
# Segmentation = None
# X =
# Y =
# Width =
# Height =
# Area = Width * Height
# Bbox = bbox(X, Y, Width, Height)
# Iscrowd =
 
# annotations.append(annotation(Annotation_Id, Image_id, Category_id, Segmentation, Area, Bbox, Iscrowd))
 
# License_Id =
# Name =
# Url =
 
# licenses.append(license(License_Id, Name, Url))
 
# with open("custom_bee_dataset.json", "w") as outfile:
#     json.dump({"info": info, "images": images, "annotations": annotations, "licenses": licenses}, outfile, indent = 4)
 
Bbox = bbox(3, 2, 6, 5)
print(vars(Bbox))
print(list(vars(Bbox).values()))
 
Annotation = annotation(0, 0, 0, None, 100, Bbox, True)
print(vars(Annotation))

[0, 'None', None]
[1, 'Pollen', None]
[2, 'Cooling', None]
[3, 'Wasp', None]
['input', 'output']
(300, 150, 3) {'cooling_output': <tf.Tensor: shape=(), dtype=float64, numpy=0.0>, 'pollen_output': <tf.Tensor: shape=(), dtype=float64, numpy=0.0>, 'varroa_output': <tf.Tensor: shape=(), dtype=float64, numpy=0.0>, 'wasps_output': <tf.Tensor: shape=(), dtype=float64, numpy=1.0>}
{'x': 3, 'y': 2, 'width': 6, 'height': 5}
[3, 2, 6, 5]
{'id': 0, 'image_id': 0, 'segmentation': None, 'area': 100, 'bbox': [3, 2, 6, 5], 'iscrowd': True}


2024-05-19 21:08:56.553448: W tensorflow/core/kernels/data/cache_dataset_ops.cc:858] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
